# Generated by Django 2.2.1 on 2019-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='morning',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('dujeong', models.CharField(blank=True, max_length=50, null=True)),
                ('cheon_station_am', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='noon',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('fromschool', models.CharField(blank=True, max_length=10, null=True)),
                ('terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('cheon_station_pm', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
